import 'dotenv/config'
import pg from 'pg'
import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '../generated/prisma/client.js'
import { readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })


function checkThreshold(
  thresholds: Record<string, number>,
  inputName: string,
  inputValue: number
) {
  const highKey = `${inputName}_high`
  const lowKey  = `${inputName}_low`

  if (thresholds[highKey] !== undefined && inputValue > thresholds[highKey]) {
    return { breached: true as const, direction: 'high', threshold: thresholds[highKey] }
  }
  if (thresholds[lowKey] !== undefined && inputValue < thresholds[lowKey]) {
    return { breached: true as const, direction: 'low', threshold: thresholds[lowKey] }
  }
  return { breached: false as const }
}

// build a single timeline entry stamped right now
function systemEntry(action: string, details?: string) {
  return {
    action,
    user: 'system',
    timestamp: new Date().toISOString(),
    ...(details ? { details } : {}),
  }
}

// p2002 is prisma's unique constraint violation code
function isDuplicate(e: unknown) {
  return (e as any)?.code === 'P2002'
}

async function main() {
  const messagesPath = join(__dirname, '../../../data/sensor_messages.json')
  const messages: any[] = JSON.parse(readFileSync(messagesPath, 'utf-8'))
  console.log(`loaded ${messages.length} messages`)

  // pull all devices once - we need thresholds for every reading check
  const devices = await prisma.device.findMany()
  const deviceMap = new Map<string, (typeof devices)[0]>()
  for (const d of devices) {
    deviceMap.set(d.device_id, d)
  }
  console.log(`loaded ${deviceMap.size} devices from db\n`)

  const stats = {
    readings:     0,
    alerts:       0,   
    breachAlerts: 0,   // generated by threshold checks on readings
    recoveries:   0,
    duplicates:   0,
    unknown:      0,   
    errors:       0,
  }

  for (const msg of messages) {
    try {
      // catch fully malformed messages - missing required shape
      if (!msg || typeof msg !== 'object' || !msg.message_type || !msg.device_id) {
        console.warn(`malformed message, skipping: ${JSON.stringify(msg ?? {}).slice(0, 120)}`)
        stats.unknown++
        continue
      }

      const device = deviceMap.get(msg.device_id)
      if (!device) {
        console.warn(`unknown device_id "${msg.device_id}", skipping message`)
        stats.unknown++
        continue
      }

      const thresholds = device.thresholds as Record<string, number>
      const ts = new Date(msg.timestamp as number)

      // reading 
      if (msg.message_type === 'reading') {
        const inputs: { input_name: string; input_value: number }[] = msg.inputs ?? []

        for (const input of inputs) {
          // store the reading
          try {
            await prisma.reading.create({
              data: {
                device_id:   msg.device_id,
                timestamp:   ts,
                input_name:  input.input_name,
                input_value: Number(input.input_value),
              },
            })
            stats.readings++
          } catch (e) {
            if (isDuplicate(e)) { stats.duplicates++; continue }
            throw e
          }

          // if reading greater than threshold then add it to alert 
          const check = checkThreshold(thresholds, input.input_name, input.input_value)
          if (check.breached) {
            const alertType = `${input.input_name}_${check.direction}`
            const detail    = `${input.input_name}=${input.input_value}, limit=${check.threshold}`
            try {
              await prisma.alert.create({
                data: {
                  device_id:    msg.device_id,
                  alert_type:   alertType,
                  severity:     'warning',  // threshold breaches default to warning
                  triggered_at: ts,
                  threshold:    check.threshold,
                  reading_value: input.input_value,
                  reading_name: input.input_name,
                  status:       'new',
                  timeline:     [systemEntry('created', `threshold breach: ${detail}`)],
                },
              })
              stats.breachAlerts++
            } catch (e) {
              if (isDuplicate(e)) { stats.duplicates++ } else { throw e }
            }
          }
        }

      // alert
      } else if (msg.message_type === 'alert') {
        try {
          await prisma.alert.create({
            data: {
              device_id:    msg.device_id,
              alert_type:   msg.alert_type,
              severity:     msg.severity     ?? 'info',
              triggered_at: ts,
              threshold:    msg.threshold    ?? null,
              reading_value: msg.reading_value ?? null,
              reading_name: msg.reading_name  ?? null,
              status:       'new',
              timeline:     [systemEntry('created')],
            },
          })
          stats.alerts++
        } catch (e) {
          if (isDuplicate(e)) { stats.duplicates++ } else { throw e }
        }

      // recovery 
      } else if (msg.message_type === 'recovery') {
        // no recovery model in schema - log it so we have a trace
        console.log(`recovery | device=${msg.device_id} | type=${msg.alert_type} | reading=${msg.reading_value ?? 'n/a'}`)
        stats.recoveries++

      // unknown 
      } else {
        console.warn(`unhandled message_type="${msg.message_type}", skipping: ${JSON.stringify(msg).slice(0, 120)}`)
        stats.unknown++
      }

    } catch (e) {
      // never crash on a single bad message 
      console.error(`error processing message: ${JSON.stringify(msg).slice(0, 120)}`)
      console.error(e)
      stats.errors++
    }
  }

  console.log('  ingest complete')
  console.log(`  readings inserted:       ${stats.readings}`)
  console.log(`  device alerts (message): ${stats.alerts}`)
  console.log(`  threshold breach alerts: ${stats.breachAlerts}`)
  console.log(`  total alerts in db:      ${stats.alerts + stats.breachAlerts}`)
  console.log(`  recoveries logged:       ${stats.recoveries}`)
  console.log(`  duplicates skipped:      ${stats.duplicates}`)
  console.log(`  unknown/malformed:       ${stats.unknown}`)
  console.log(`  errors:                  ${stats.errors}`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => pool.end())